// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/app/_middleware.ts";
import * as $2 from "./routes/app/index.tsx";
import * as $3 from "./routes/app/logout.tsx";
import * as $4 from "./routes/auth.tsx";
import * as $5 from "./routes/callback.tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LoginCallback.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/app/_middleware.ts": $1,
    "./routes/app/index.tsx": $2,
    "./routes/app/logout.tsx": $3,
    "./routes/auth.tsx": $4,
    "./routes/callback.tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LoginCallback.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
